-- Users table is managed by Supabase Auth

-- Matches table
create table matches (
  id bigint generated by default as identity primary key,
  team_a text not null,
  team_b text not null,
  match_time timestamptz not null,
  odds_a float8 not null default 1.0,
  odds_b float8 not null default 1.0,
  odds_draw float8 not null default 1.0,
  status text not null default 'scheduled' -- scheduled, live, finished, canceled
);

-- Bets table
create table bets (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  match_id bigint references matches not null,
  bet_on text not null, -- 'team_a', 'team_b', or 'draw'
  amount numeric not null,
  status text not null default 'placed', -- placed, won, lost, canceled
  created_at timestamptz default now()
);

-- RLS policies
alter table matches enable row level security;
create policy "Public matches are viewable by everyone." on matches for select using (true);

alter table bets enable row level security;
create policy "Users can view their own bets." on bets for select using (auth.uid() = user_id);
create policy "Users can place bets." on bets for insert with check (auth.uid() = user_id);
