-- Users table is managed by Supabase Auth

-- Matches table
create table matches (
  id bigint generated by default as identity primary key,
  team_a text not null,
  team_b text not null,
  match_time timestamptz not null,
  odds_a float8 not null default 1.0,
  odds_b float8 not null default 1.0,
  odds_draw float8 not null default 1.0,
  status text not null default 'scheduled' -- scheduled, live, finished, canceled
);

-- Bets table
create table bets (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  match_id bigint references matches not null,
  bet_on text not null, -- 'team_a', 'team_b', or 'draw'
  amount numeric not null,
  status text not null default 'placed', -- placed, won, lost, canceled
  created_at timestamptz default now()
);

-- Transactions table
create table transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  amount numeric not null,
  type text not null, -- 'deposit', 'withdrawal', 'bet', 'win'
  created_at timestamptz default now()
);

-- RLS policies
alter table matches enable row level security;
create policy "Public matches are viewable by everyone." on matches for select using (true);
create policy "Admins can manage matches." on matches for all using (
  (select auth.jwt() ->> 'role' = 'admin')
);


alter table bets enable row level security;
create policy "Users can view their own bets." on bets for select using (auth.uid() = user_id);
create policy "Users can place bets." on bets for insert with check (auth.uid() = user_id);
create policy "Admins can view all bets." on bets for select using (
  (select auth.jwt() ->> 'role' = 'admin')
);

alter table transactions enable row level security;
create policy "Users can view their own transactions." on transactions for select using (auth.uid() = user_id);
create policy "Admins can view all transactions." on transactions for select using (
  (select auth.jwt() ->> 'role' = 'admin')
);
