import Head from 'next/head'
import { ThemeSwitcher } from '@/components/ThemeSwitcher'
import { useUser } from '@repo/hooks/useUser'
import Link from 'next/link'

export default function Home() {
  const user = useUser()

  return (
    <div className="flex flex-col items-center justify-center min-h-screen py-2 dark:bg-gray-900 dark:text-white">
      <Head>
        <title>Ultra Betting App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
        <div className="absolute top-4 right-4">
          <ThemeSwitcher />
        </div>
        <h1 className="text-6xl font-bold">
          Welcome to <span className="text-blue-600">Ultra Betting!</span>
        </h1>

        <p className="mt-3 text-2xl">
          The most futuristic betting platform ever.
        </p>

        {user ? (
          <div className="mt-6">
            <p>Welcome, {user.email}</p>
          </div>
        ) : (
          <div className="mt-6">
            <Link href="/auth/login" className="mx-2 p-2 border rounded">
              Login
            </Link>
            <Link href="/auth/register" className="mx-2 p-2 border rounded">
              Register
            </Link>
          </div>
        )}
      </main>
    </div>
  )
}
